### ISSUE TITLE
Stable or unmaintained?

### ISSUE THREAD

**Issue by YeungOnion** [shuoli84/sweep-bptree#25]
Hi! Not technically an issue, but I've a question about the crate's stability. 

Considering using this as a dependency or building out my own. I like the ideas here, but if I'm going to use it, I'd like to contribute back with tests and docs (likely not features and performance enhancements) as I use it.

**Comment by shuoli84** [comment]
Hi, @YeungOnion Sorry for the late reply, I missed the notification by somehow.. feel free to open pr and issue. I am more than happy to review or contribute.
